heritagefund/funding-frontend

.github/workflows/continuous-integration-workflow.yml

Deploy to PaaS using GitHub actions

deploy to paas

---

config/environments/production.rb

add production host to mailer

---

app/controllers/organisation/organisation_type_controller.rb
app/models/organisation.rb
app/views/layouts/application.html.erb
app/views/organisation/organisation_type/type.html.erb
app/views/partials/_form_group_errors.html.erb
app/views/partials/_summary_errors.html.erb
config/environment.rb
config/locales/en.yml

Raised issue #40 to revisit this as a piece of technical debt at a later date.

Validation checks for organisation type form

---

app/models/project.rb

refactor so we can lookup organisation directly rather than through user. See: https://guides.rubyonrails.org/association_basics.html#the-has-one-through-association

refactor: create association between project and organisation through user

---

app/views/project/project_support_evidence/project_support_evidence.html.erb

For now, add a TODO, so we can prioritise fixing this alongside other work.

remove download link, add todo

---

app/models/project_cost.rb
db/migrate/20200103123144_create_project_costs.rb
db/migrate/20200103123718_add_project_ref_to_project_costs.rb
db/schema.rb
test/factories/project_costs.rb
test/models/project_cost_test.rb

Adds migration for Project Costs table in advance of functionality.

Project costs migration

---

app/views/layouts/application.html.erb

This branch fixes the govuk component javascript initialisation issue.
The word count component now behaves correctly.

fix for js issues

---

app/models/volunteer.rb
db/migrate/20200106100556_create_volunteers.rb
db/migrate/20200106101655_add_project_ref_to_volunteers.rb
db/schema.rb
test/factories/volunteers.rb
test/models/volunteer_test.rb

Add model and migrations to support volunteer functionality.

Add volunteers migration

---

README.md
manifest-research.yml

Add Research manifest

---

app/views/project/project_difference/show.html.erb

As per wording changes in https://trello.com/c/rSo5VpE6.

Updated content on project difference page

---

app/assets/stylesheets/_settings.general.scss
app/assets/stylesheets/components/_toolbar.scss
app/views/layouts/application.html.erb
app/views/partials/_phase-banner.html.erb
app/views/project/capital_works/capital_works.html.erb

Adds BETA phase banner

---

app/helpers/project/project_costs_helper.rb
app/views/project/project_costs/show.html.erb

fixes exception in case cost amount is empty. (allows for empty amount but we should restrict this by other validations) CC @Ellayanor

make amount field required on client side

---

app/views/project/project_dates/show.html.erb

CC @Ellayanor (noticed this using Firefox accessibility dev tools)

accessibility: fix labels for date fields

---

app/controllers/project/project_grant_request_controller.rb
app/views/project/project_grant_request/project_grant_request.html.erb
config/routes.rb

Basic content will need wiring up

project grant request content

---

app/views/project/project_support_evidence/project_support_evidence.html.erb

Resolving TODO now S3 permissions issue is resolved.
This reverts commit 6085c6f93afbe1fe7b0d0d7b750b4cd20f380111.

Revert "remove download link, add todo"

---

app/views/project/project_location/project_location.html.erb

fixes broken location ID label I found

---

app/views/project/project_permission/show.html.erb

Tiny content change as per one of the critical items in https://trello.com/c/gpjS50Au.

Updated content for conditional text field label

---

app/models/non_cash_contribution.rb
app/models/project.rb
db/migrate/20200113130219_add_non_cash_contributions.rb
db/migrate/20200113130313_add_project_to_non_cash_contributions.rb
db/schema.rb

This pull request adds migrations for the non-cash contributions table and the relevant model, and amends the `Projects` model to include a reference to the `NonCashContributions` model.

Added migrations and model for non-cash contributions

---

app/helpers/project/project_non_cash_contributions_helper.rb
app/views/project/project_non_cash_contributions/show.html.erb

Non cash contributions HTML table added. Waiting for dynamic total value to be added.

adds table and tidies mark-up for non-cash-contributions page

---

.github/workflows/continuous-integration-workflow.yml

Cache yarn dependencies to speed up build.

cache yarn dependencies

---

app/controllers/project/project_application_submitted_controller.rb
app/controllers/project/project_declaration_controller.rb
app/views/project/project_application_submitted/show.html.erb
app/views/project/project_declaration/declaration_confirmed.html.erb
config/routes.rb

This pull request adds a stubbed page for 'Application submitted' and wires it into the current service flow.
We'll need to revisit this to confirm content and wire it into the Salesforce submission process.

Added stubbed application submitted page

---

db/migrate/20200123093801_set_is_partnership_default.rb
db/schema.rb

https://trello.com/c/SJEAxCcL/1049-default-declaration-fields

default is partnership to false

---

app/controllers/project/project_declaration_controller.rb
app/models/project.rb
app/views/project/project_declaration/show_declaration.html.erb
config/locales/en.yml

Added server-side validation to partnerships

---

app/controllers/project/project_cash_contribution_controller.rb

See [this](https://trello.com/c/W53LYaNy) Trello card for details.
Note that this won't work without the changes from #171 being merged in first.

Always direct to grant request page from cash contributions question

---

app/controllers/project/project_capital_works_controller.rb
app/models/project.rb

See [this](https://trello.com/c/3xJi0xSx) Trello card for context.

Removed validation of capital work file

---

app/controllers/project/project_costs_controller.rb
app/models/project.rb
app/views/project/project_costs/show.html.erb
config/locales/en.yml
config/routes.rb

This pull request adds a validation check to confirm the presence of associated project costs, as per [this](https://trello.com/c/kIXpjTKo) Trello card.

Added validation to confirm presence of project costs

---

app/controllers/project/project_costs_controller.rb
app/models/project_cost.rb
app/views/project/project_costs/show.html.erb
config/routes.rb

This pull request adds the ability to delete a project cost from the 'Project costs' page.
As well, this pull request contains the validation for the project cost description, which was previously found to be missing.

Implemented deletion of project costs

---

app/views/project/project_cash_contribution/show.html.erb

Fixes exception if secured is nil.

add more safe navigation to secured display

---

app/views/layouts/application.html.erb
app/views/partials/_tracking_tags.html.erb
config/environments/production.rb

adds tracking snippet to layout

---

Gemfile
Gemfile.lock
app/jobs/sentry_job.rb
config/initializers/sentry.rb

Add sentry dependency on production and associated config.

Add sentry

---

app/controllers/concerns/project_context.rb
app/controllers/project/project_title_controller.rb
app/views/dashboard/show.html.erb

Block access to project once submitted.

Submitted state

---

Gemfile

scope production dependencies to staging

---

config/environments/development.rb

there is no need for this to be in env as it does not send emails from development anyway.

do not get support email from environment in development

---

app/views/devise/sessions/new.html.erb
app/views/layouts/application.html.erb
app/views/support/show.html.erb

Updates support content.
Remove service status link from the footer.
Calls out account login hint more prominently.

Update support content

---

manifest-production.yml
manifest-research.yml
manifest-staging.yml

review once https://github.com/cloudfoundry/ruby-buildpack/issues/120 is resolved

lock to old version of buildpack

---

.github/workflows/continuous-integration-workflow.yml

This adds a deployment to production. The authentication step is broken out as it is shared.

add production deployment

---

app/controllers/organisation/mission_controller.rb
app/views/organisation/mission/show.html.erb

This pull request contains some tidying and slight refactoring of the controller and view for the 'Organisation mission' section of the service.

General tidying of organisation mission section

---

app/views/layouts/application.html.erb

A digital service design CivicTech GOVUK style nod to Tom Steinberg the first digital lead here at the National Lottery Heritage Fund and co founder of our team.

A thank you

---

app/controllers/organisation/numbers_controller.rb
app/models/organisation.rb
app/models/project.rb
app/views/organisation/numbers/show.html.erb
db/migrate/20200131151215_change_company_number_field_to_string.rb
db/schema.rb

This pull request converts the organisation company number attribute from an integer to a string.

Converted organisation company number from integer to string

---

app/controllers/project/project_cash_contribution_controller.rb
app/controllers/project/project_support_evidence_controller.rb

I think I removed this in error in a previous pull request - without this instance variable, the conditional JavaScript for file uploads was not being pulled into the relevant pages.

Reinstated @has_file_upload instance variable

---

app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/_banner.scss
app/views/devise/sessions/new.html.erb

New banner component
Updated content on sign-in page

Updates for clearer pilot information

---

spec/controllers/organisation/type_controller_spec.rb

This pull request adds integration tests for the `organisation/type_controller`.

Added integration tests for organisation type controller

---

spec/controllers/organisation/numbers_controller_spec.rb

This pull request adds integration tests for the `organisation/numbers_controller`.

Added integration tests for organisation numbers controller

---

spec/helpers/project/calculate_total_helper_spec.rb
test/factories/project.rb

there probably is a nicer way to make the associated models with factory bot. But this tests the functionality.

add test for calculate costs

---

spec/factories/users.rb
spec/fixtures/files/example.txt
spec/helpers/project/calculate_total_helper_spec.rb
spec/jobs/application_attachments_to_salesforce_job_spec.rb
spec/rails_helper.rb
test/factories/project.rb

Adds tests for attachment uploader
(also assorted changes to fixtures and test environment required to support these tests)

add tests for attachment uploader

---

app/views/organisation/about/address_results.html.erb
app/views/user/address/address_results.html.erb

noticed these pages were missing titles whilst writing tests.

add missing page titles

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

add database cleaner for rspec tests

---

app/models/user.rb

remove unused method from auth0 spike

remove unused method

---

app/helpers/nlhf_form_builder.rb
app/views/organisation/about/about.html.erb
app/views/organisation/mission/show.html.erb
app/views/organisation/numbers/show.html.erb
app/views/organisation/type/show.html.erb
app/views/project/project_best_placed/show.html.erb
app/views/project/project_capital_works/show.html.erb
app/views/project/project_cash_contribution/question.html.erb
app/views/project/project_check_answers/show.html.erb
app/views/project/project_dates/show.html.erb
app/views/project/project_description/show.html.erb
app/views/project/project_difference/show.html.erb
app/views/project/project_heritage/show.html.erb
app/views/project/project_involvement/show.html.erb
app/views/project/project_location/entry.html.erb
app/views/project/project_location/project_location.html.erb
app/views/project/project_matters/show.html.erb
app/views/project/project_non_cash_contributions/question.html.erb
app/views/project/project_outcomes/show.html.erb
app/views/project/project_permission/show.html.erb
app/views/project/project_title/show.html.erb
app/views/user/address/show.html.erb
app/views/user/details/show.html.erb

@paulmsmith this should work as we discussed whereby it sets some defaults which are all overridable and otherwise behaves like a normal `submit` method.

adds Save and Continue form builder method

---

app/controllers/organisation/about_controller.rb
spec/controllers/organisation/about_controller_spec.rb

This pull request adds integration tests for the `organisation/about_controller`, as well as some general tidying of the controller itself.

Added organisation about controller integration tests

---

app/controllers/project/outcomes_controller.rb
app/models/project.rb
app/views/project/outcomes/show.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/project/outcomes_controller_spec.rb

This pull request adds integration tests for the `project/outcomes_controller`.

Added integration tests for project outcomes controller

---

app/controllers/project/new_project_controller.rb
spec/controllers/project/new_project_controller_spec.rb

This pull request adds integration tests for the `project/new_project_controller`.

Added integration test for new project controller

---

app/views/layouts/application.html.erb

…sadly leaving the fund after 25 years, all the best Sue!

A tribute to Sue

---

manifest-production.yml
manifest-research.yml
manifest-staging.yml

The latest buildpack _should_ work now as upstream issue has been resolved.

switch to latest upstream buildpack

---

app/views/dashboard/show.html.erb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/unlocks/new.html.erb
app/views/home/show.html.erb
app/views/organisation/about/about.html.erb
app/views/organisation/about/address_results.html.erb
app/views/organisation/about/postcode_lookup.html.erb
app/views/project/application_submitted/show.html.erb
app/views/project/grant_request/show.html.erb
app/views/project/project_cash_contribution/question.html.erb
app/views/project/project_costs/show.html.erb
app/views/project/project_dates/show.html.erb
app/views/project/project_location/address_results.html.erb
app/views/project/project_location/entry.html.erb
app/views/project/project_location/postcode_lookup.html.erb
app/views/project/project_location/project_location.html.erb
app/views/user/address/address_results.html.erb
app/views/user/address/postcode_lookup.html.erb
app/views/user/address/show.html.erb
app/views/user/details/show.html.erb

This pull request updates the remaining views files to use the page titles partial.
Closes #76 .

Updated remaining page titles to use partial

---

manifest-production.yml
manifest-research.yml
manifest-staging.yml

try this fix suggested by PaaS team.

point explicitly to latest tag

---

manifest-production.yml
manifest-staging.yml

speculative fix for buildpack issue.

move buildpack to top level

---

app/views/devise/sessions/new.html.erb

Now adds 'North of England' to the content panel at the top to indicate to those users they can apply via the new service. 
Leaving in draft mode because we are blocked on merging until we get the green light from @Ellayanor and Alice.

Updates beta criteria content on sign in page

---

app/controllers/concerns/organisation_context.rb
app/controllers/concerns/project_context.rb
spec/controllers/concerns/organisation_context_spec.rb
spec/controllers/concerns/project_context_spec.rb

This pull request adds tests for the `OrganisationContext` and `ProjectContext` controller concerns.

Added tests for project and organisation controller concerns

---

app/controllers/user/details_controller.rb

This pull request contains a fix for a `TODO` item found within the `user/details_controller`.

Fixed a TODO on the user details controller

---

db/migrate/20200330102720_create_flipper_tables.rb
db/schema.rb

This pull request adds a database migration file for `Flipper`-generated tables.

Added a migration to add Flipper tables

---

app/helpers/project/calculate_total_helper.rb

Small refactor. Use [sum](https://api.rubyonrails.org/classes/ActiveRecord/Calculations.html#method-i-sum) Rails helper instead of reduce.

use sum rails helper instead of reduce

---

app/views/devise/sessions/new.html.erb

Fixes issue found in accessibility audit https://trello.com/c/QrqR34k7

add H1 on sign in page

---

app/mailers/notify_mailer.rb
app/models/user.rb

Reverts heritagefund/funding-frontend#386

Revert "Reinstates Devise asynchronous sending"

---

yarn.lock

Selectively updates yarn sub-dependencies with security issues using the technique described in: https://stackoverflow.com/a/60832612/238230

update selected yarn dependencies

---

app/views/project/dates/show.html.erb

fixes issues found in accessibility review https://trello.com/c/IOxJbSsw

fix duplicate ID and missing ARIA label

---

app/views/help/cookie_details.html.erb
config/locales/help/cookie_details/cy.yml
config/locales/help/cookie_details/en.yml

[Ticket here](https://trello.com/c/P6PLOCo1/1761-abstract-content-from-cookie-pages-in-funding-frontend)

1761-cookie-content-translation 

---

app/models/project.rb
lib/apis/salesforce/salesforce_api.rb

Add in check for medium/eoi/pef for user acting as legal sig

Add in check for medium/eoi/pef for user acting as legal sig

---

.github/workflows/azure-deploy-uat.yml

Changed the trigger to be the push to the push to the `feature/bitzesty-ci-containerisation` branch

Feature/ Azure uvt pipeline trigger

---

config/environments/uat.rb

Set PaperTrail as default logger for `uat` environment.

Feature/Azure PaperTrail

---

config/environments/uat.rb

adding azure host config to uat.rb to enable cors policy error to fix. match training.rb to see if this fixes the cors policy error.

adding azure host config to uat.rb to enable cors policy error to fix

---

.github/workflows/azure-deploy-civmiguat.yml
.github/workflows/azure-deploy-production.yml
.github/workflows/azure-deploy-research.yml
.github/workflows/azure-deploy-training.yml
.github/workflows/azure-deploy-uat.yml
config/application.rb

- Cherry-picked commit to have pipeline actions renamed so they are easier to tell apart + have deploy trigger to be set to manual.
- Modified PaperTrail initialization to check if all necessary ENV variables are set as during asset compilation we are setting only bare minimum of the ENV variables.
Compilation error triggered here: https://github.com/heritagefund/funding-frontend/actions/runs/6482891357/job/17603465047 
```
#21 [build 7/7] RUN SKIP_SALESFORCE_INIT=true SKIP_FLIPPER_INIT=true SECRET_KEY_BASE=DUMMY ./bin/rails assets:precompile
#21 1.645 rails aborted!
#21 1.645 KeyError: key not found: "PAPERTRAIL_DESTINATION_URI"
#21 1.646 /rails/config/application.rb:75:in `fetch'
```

Feature/CI containerisation - assets precompile fix

---

.github/workflows/azure-ci.yml
config/application.rb
config/environments/civmiguat.rb
config/environments/production.rb
config/environments/research.rb
config/environments/staging.rb
config/environments/training.rb
config/environments/uat.rb

Added CI pipeline to test (when PR is opened) & then build/deploy when PR is merged using Azure & Docker.
Also moved PaperTrail config to respective environment files (added config for staging)
Brought back `log` folder as it was causing error when building Docker image
Part of the work migrating the app from CF to Azure.

Feature/bitzesty Azure CI pipeline
