app/controllers/health_controller.rb, config/routes.rb, manifest.yml, test/controllers/health_controller_test.rb
Cloud Foundry can make use of a health check HTTP endpoint
(https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html#health_check_uri),
and requires this to be added to an application. Rather than
using the index route of the application, it makes more sense
to add a specific route for serving this purpose. We can expand
upon this later to add a health check that will also check
application dependencies such as databases or other components.
=> Added a basic health check endpoint for use in CF

.github/workflows/continuous-integration-workflow.yml
We should run CI on all branches but only deploy on `master`
=> run tests on all pushes, only deploy on master

app/models/organisation.rb, db/migrate/20191211142201_add_type_to_organisations.rb, db/schema.rb
Each organisation has a type associated with it. I've added this
as a new type within the database migration when applying it to
the new column org_type - this will stop data that doesn't match
any of the values of the enumerator from being added within this
field. As well as adding this database migration, I've also added
the relevant field to the model to enable this.
=> Added migration containing org_type column

app/models/user.rb, db/migrate/20191216113731_add_confirmable_to_devise.rb, db/schema.rb, test/controllers/dashboard_controller_test.rb, test/controllers/projects_controller_test.rb
https://trello.com/c/KkmAxQK2/871-implement-a-confirm-email-step-in-the-account-registration-flow
Note: locally you should see the confirm URL in the console you can use to test this.
Also, this uses the default flow provided by Devise which is quite clunky and seems to make you re-login after confirming. We should review this flow with @paulmsmith to see if it can be improved.
=> Make users confirm email

app/views/organisation/organisation_summary/show.html.erb
I was getting an exception on staging because my organisation did not have one of the fields populated
```
ActionView::Template::Error (undefined method `humanize' for nil:NilClass): 
```
We can the safe navigation operator to not throw an exception in this case.
=> use safe navigation operator for humanize

db/seeds.rb
Adds an example user when `db:setup` or `db:seed` is run. This should ease the burden of having to register for local development.
=> add seed user

app/controllers/organisation/organisation_signatories_controller.rb, app/models/legal_signatory.rb, app/views/organisation/organisation_signatories/signatories.html.erb, config/locales/en.yml
This pull request adds validation to the legal signatories form for an organisation.
I haven't split the summary display of errors out into a partial, as this might be the only place that we need to loop through an array of objects before looping through their error messages. If this is something that we end up having to do again elsewhere, then this piece of code can be refactored into a partial which takes a set of parameters.
=> Added validation for organisation legal signatories form

config/application.rb
Switching to en-GB default locale broke Devise messages as they are set for `en`.
Setting this fallback option uses `en` where `en-GB` is not available.
=> bugfix: enable i18n fallbacks

db/migrate/20200102152101_add_location_to_projects.rb, db/schema.rb
These fields are necessary to replicate the organisation address structure for a project.
=> Generated migration for project location fields

app/controllers/project/project_location_controller.rb, app/models/project.rb, app/views/project/project_location/project_location.html.erb, config/locales/en.yml, config/routes.rb
This pull request adds the functionality for being able to specify that a project location is taking place in the same place as the corresponding organisation address.
I'll be picking up the inverse functionality in a separate branch and pull request.
=> Added functionality for project location mirroring organisation address

db/migrate/20200103090702_add_difference_to_projects.rb, db/schema.rb
This pull request adds a migration to add a `difference` column to the `projects` table, relevant to the 'What difference will your project make?' page.
=> Added a migration to add difference column to projects table

db/migrate/20200103104247_add_matter_to_projects.rb, db/schema.rb
This pull request adds a new migration script to add a `matter` column to the `projects` table. This is in relation to the 'Why does your project matter' page in the journey.
=> Added migration file for adding matter column to projects table

app/controllers/project/project_dates_controller.rb, app/views/project/project_dates/show.html.erb
> I think this is causing this issue on a subsequent page, where the notice is being retained and displayed erroneously here. CC @stuartmccoll
> <img alt="Screenshot 2020-01-03 at 10 45 29" width="584" src="https://user-images.githubusercontent.com/1764158/71719457-521cd180-2e16-11ea-9717-8d83550d0748.png">
This fixes the above issue referenced in #62.
Note that we'll have to avoid using the built-in `flash` keys as these are used within the registration/login flow.
=> Removed usage of flash.notice on project dates page

db/migrate/20200103145613_add_heritage_description_to_projects.rb, db/schema.rb
This pull request includes a migration which adds a `heritage_description` column to the `projects` table - this is relevant to the 'The heritage of your project: how do you plan to make it available once the project is over?' page of the service journey.
=> Added migration for heritage_description column of projects table

db/migrate/20200106080153_add_best_placed_description_to_projects.rb, db/schema.rb
This migration script adds the best_placed_description column to the projects table. This is related to the 'Why is your organisation best placed to deliver this project' page of the service journey.
=> Added migration for best_place_description column

db/migrate/20200106100540_add_involvement_description_to_projects.rb, db/schema.rb
This commit adds a migrations script to add the involvement_description column to the projects table. This is related to the 'How will your project involve a wider range of people?' page of the service journey.
=> Add involvement_description migration for projects table

.github/workflows/continuous-integration-workflow.yml
Workaround for upstream issue https://github.community/t5/GitHub-Actions/Errors-on-updating-apt-cache-for-azure-cli/m-p/42743#M5095
=> download CF CLI from S3 and install from .deb file

db/migrate/20200107095122_add_permission_to_projects.rb, db/schema.rb
This commit adds a migration script to add two new columns to the projects database. These are `permission_type`, which will be used to determine the type of permission selected by a user that their project requires, and `permission_description` which will be used to store details of the permission required by their project.
=> Added migration script for project permission columns

db/migrate/20200107154043_add_capital_work_to_projects.rb, db/schema.rb
This commit adds a migrations script containing a new column to the projects table - `capital_work` is a boolean column to indicate whether or not capital work will be part of a project.
=> Added a migration script for capital_work column to projects table

app/views/devise/shared/_error_messages.html.erb
This displays errors and notifications and errors from devise.
Fixes #62 
@paulmsmith we need to handle the information messages generated by devise. For now I added them in the error area unstyled but they may be more suited to an overlay style or something which denotes success.. 
Please can you figure out a design for this.
=> Display account error and info messages.

app/models/project.rb, test/fixtures/organisations.yml, test/fixtures/projects.yml, test/models/project_test.rb
This pull request adds some of the missing model fields to the `to_salesforce_json` method for the `project` model, with dummy data and real data where this is available.
=> Updated to_salesforce_json method of project model

db/migrate/20200109142055_add_outcomes_to_projects.rb, db/schema.rb
This commit adds a new migration script containing the eight `boolean` columns for each outcome on the project outcomes page, as well as the eight `text` columns for the relating descriptions.
=> Added project outcomes migration script

.github/workflows/continuous-integration-workflow.yml
We can speed up the build by using the new caching ability provided by GitHub actions to cache dependencies.
See: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/caching-dependencies-to-speed-up-workflows for context.
=> Cache gemfile dependencies

app/views/project/project_support_evidence/project_support_evidence.html.erb
Adding this pull request but need some help @gidsg @stuartmccoll .
I've made the design changes but it looks like the ERB needs updating. Instead of looping out a new table row with each item, it seems there are two separate loops for the descriptions and filenames. Can this be made more like the costs table please?
=> updates the design for evidence of support page

config/routes.rb, test/controllers/home_controller_test.rb
This pull request updates the root of the application to point at two different pages depending on whether or not a user has authenticated. Unauthenticated users are directed to the sign-in page, authenticated users are directed to the dashboard page.
Previously, we were directing all root requests to the dashboard page. When a user wasn't signed in, this would trigger the fact that the user wasn't authenticated and then direct them back to the sign-in page with the 'You must be signed in...' error message displayed.
I've tested, and this *does* also fix the email validation confirmation being displayed.
=> Updated routes to fix sign-in error message display

app/views/devise/registrations/new.html.erb
I noticed during accessibility testing that the password input field on the new account creation page was gaining autofocus when the page initially loaded. Upon inspection, it looks like we were setting autofocus to true on both the email_field and password_field elements. This commit fixes the issue by removing the autofocus attribute from the password_field element.
=> Remove duplicate autofocus attribute

app/views/dashboard/show.html.erb
Turbolinks broke the functionality of the `home_controller`, where we create a new organisation and amend the start button link to point to the organisation section of the form if a user didn't already have an organisation, or amend the start button link to point straight to the projects section of the form if they did.
I'm not sure whether this crept in as part of the JavaScript changes recently, but setting `data-turbolinks="false"` on the button element stops it from seemingly rendering the next page twice. We've discussed removing turbolinks completely, so I'll raise a separate issue to investigate this.
=> Stopped turbolinks breaking the flow of the organisation section

app/controllers/project/project_volunteers_controller.rb, app/models/project.rb, app/models/volunteer.rb, app/views/project/project_volunteers/show.html.erb, config/locales/en.yml
This pull request adds validation to the project volunteers page. Note that this is done in the same way that we have done non-cash contributions, using `flash` to populate form values when we re-render upon validation failure, which we've said that we'll revisit when we have time.
I've also left in the `TODO` around splitting the summary of errors out into a partial, or refactoring the existing partial to be able to accommodate nested forms.
=> Added validation to project volunteers page

app/views/project/project_location/project_location.html.erb
This pull request changes the labels for project location radio buttons as per https://trello.com/c/Y57fd3yK.
=> Content change to radio buttons for project location

app/views/project/project_support_evidence/project_support_evidence.html.erb
This pull request adds functionality to the 'Save and continue' button on the 'Evidence of support' page.
Note that we've discussed investigating whether these should be form buttons or links with button roles, which has been raised in #140.
=> Added link to supporting evidence page Save and continue button

app/controllers/organisation/organisation_about_controller.rb
This is a debugging tool which is no longer included in the production dependencies causing the deploy to fail.
=> remove pry invocation

app/controllers/concerns/organisation_context.rb, app/controllers/organisation/organisation_about_controller.rb, app/controllers/organisation/organisation_mission_controller.rb, app/controllers/organisation/organisation_numbers_controller.rb, app/controllers/organisation/organisation_signatories_controller.rb, app/controllers/organisation/organisation_summary_controller.rb, app/controllers/organisation/organisation_type_controller.rb, app/helpers/organisation_helper.rb
Similar to how we replaced the `set_project` usage for project controllers, this pull request does the same for organisation controllers.
As well as that, it adds extra checks to ensure that the organisation which is being accessed is related to the current user.
Closes #155
=> Replaced set_organisation helper use with a controller context

app/controllers/project/project_support_evidence_controller.rb, app/models/evidence_of_support.rb, app/models/project.rb, app/views/project/project_support_evidence/show.html.erb, app/views/project/project_support_evidence/show.js.erb, config/locales/en.yml, config/routes.rb, db/migrate/20200122094326_add_evidence_of_support.rb, db/migrate/20200122094550_add_project_ref_to_evidence_of_support.rb, db/schema.rb
This pull request splits supporting evidence into it's own model and adds validation to the relevant page.
Note that it's the same validation used on similar pages, I'll revisit DRY-ing this and making it reusable and slightly more robust once the entire journey is wired up and in place.
=> Split evidence of support into own model and added validation

app/controllers/home_controller.rb, app/views/home/show.html.erb, app/views/project/new_project/new_project.html.erb, config/routes.rb
This pull request extends the existing validation that takes place to determine whether or not a user should be directed to the organisation or project sections of the service. 
Previously, we were only checking to see whether a user had a related organisation, directing them to the project section if so or to the organisation section if not.
Now, we check to see whether the user has a related organisation and whether or not this organisation has the mandatory organisation attributes populated. If not, we direct the user to the organisation section of the service. If the user does not have an organisation, we still direct them into the organisation section of the service. If the user has an organisation and this organisation has the necessary mandatory attributes populated then we direct …
=> Updated initial organisation validation

app/controllers/project/project_grant_request_controller.rb, app/views/project/project_grant_request/show.html.erb
This commit fixes a bug which could occur on the 'Your Grant Request' page if a user had navigated to this page without setting any project costs or cash contributions.
Previously, the `@final_grant_amount` instance variable would have a value of nil, which would cause an error when the view attempted to use this variable.
Setting .to_i on the values inside the `@final_grant_amount` calculation implicitly converts them to 0 if they are nil.
As well, this commit adds an additional message to the 'Your grant request' page in case a `@final_grant_amount` of 0 is present.
=> Implemented fix to nil-value bug on grant request page

app/controllers/project/project_declaration_controller.rb
This pull request adds functionality to run the Salesforce application submission job if a user has confirmed that they have read the declaration.
=> Added running of Salesforce job to declaration controller

app/models/project.rb, test/fixtures/users.yml, test/models/project_test.rb
This pull request adds functionality to retrieve the correct data for the `mainContact` fields of the Salesforce payload, and also contains updates to the relevant test and fixtures.
=> Added contacts details to Salesforce payload

app/models/project.rb
Currently even if legal signatory 2 is not populated it creates a record with an ID on save. This extra check stops the child element being erroneously created in that case.
=> add field check before populating legal signatory 2

app/controllers/project/project_grant_request_controller.rb, app/views/project/project_grant_request/show.html.erb
This is probably really noddy but does what we intend for the grant request page.
- Value greater than funding programme maximum will not let users continue and prompts to view costs and contributions
- Will not let users continue if their grant request is invalid due to cash contributions being higher than project costs.
@stuartmccoll or @gidsg - This will likely need refactoring but hopefully you can see how I've structured the content, mark-up depending on those scenarios.
=> adds in logic to view to validate grant request

app/views/project/project_cash_contribution/show.html.erb
Previously we weren't displaying the actual `:secured` value for cash contributions in the table on this page. This pull request addresses this - removing the `x_` from the value for 'Not sure', humanising each value and then replacing `Yes ` with `Yes, ` for readability.
As well, this fixes a bug where cash contribution calculations included 'hidden' fields which weren't being displayed in the table because they did not have descriptions.
The `link_to` line was causing 500 errors, which has been fixed also.
=> Made cash contributions secured value display dynamically

app/controllers/project/project_volunteers_controller.rb, app/views/project/project_volunteers/show.html.erb, config/routes.rb
This pull request implements the functionality to delete volunteers that have been added to a project. This follows the same pattern used in #182 for the deletion of project costs.
=> Added deletion of project volunteers

app/controllers/project/project_non_cash_contributions_controller.rb, app/views/project/project_non_cash_contributions/show.html.erb, config/routes.rb
This pull request implements the functionality to delete non-cash contributions that have been added to a project. This follows the same pattern used in #182 for the deletion of project costs.
=> Added delete functionality to non-cash contributions

app/controllers/project/project_cash_contribution_controller.rb, app/views/project/project_cash_contribution/show.html.erb, config/routes.rb
This pull request implements the functionality to delete cash contributions that have been added to a project. This follows the same pattern used in #182 for the deletion of project costs.
This method will also remove the related attachment from the `active_storage_attachments` and `active_storage_blobs` tables.
=> Added delete functionality to cash contributions

app/controllers/project/project_support_evidence_controller.rb, app/views/project/project_support_evidence/show.html.erb, config/routes.rb
This pull request implements the functionality to delete evidence of support that has been added to a project. This follows the same pattern used in #182 for the deletion of project costs.
This method will also remove the related attachment from the active_storage_attachments and active_storage_blobs tables.
=> Added delete functionality to evidence of support

app/views/project/project_non_cash_contributions/show.html.erb
This pull request adds missing error classes to form inputs on the non-cash contributions page if relevant errors are present.
=> Added missing error classes to form inputs

app/controllers/concerns/object_errors_logger.rb, app/controllers/organisation/type_controller.rb, app/views/organisation/type/show.html.erb, app/views/partials/_page_title.html.erb
This pull request contains some general tidying and slight refactoring of the controller and view for the 'What type of organisation will be running your project' page.
I've created a partial to be used for the `title` element of each page, which is implemented here.
As well, I've created a generic `ObjectErrorsLogger` class with a `log_errors` method that we can use to log any object validation errors at a `debug` level.
=> Tidied organisation type controller and view

app/models/legal_signatory.rb
This is a workaround to the issue described in https://trello.com/c/Eh8gqH6y/1072-trustee-email-cannot-match-main-contact-email
=> enforce legal signatory is different than main contact

app/controllers/organisation/numbers_controller.rb, app/models/organisation.rb, app/views/organisation/numbers/show.html.erb, config/locales/en.yml, db/migrate/20200128141927_change_charity_number_column_type.rb, db/schema.rb
This pull request removes validation of an organisation's charity number. This came from the following note from Alice:
> Scottish Charities have letters in them, not just numbers
=> Removed validation of organisation charity number

app/views/project/project_support_evidence/show.html.erb
This pull request fixes an issue with the `label` element on the Evidence of support page. @Jo-Arthur-NLHF reported that the file upload field was not being read out well by screen reader software - I've investigated and the label wasn't correctly attributed to the input field. Hopefully this will fix the issue.
See https://trello.com/c/8LFdLLIJ for context.
=> Fixed label for evidence of support files upload field

app/views/project/project_capital_works/show.html.erb
This pull request fixes a `label` element on the Capital work page. See #216 for context.
=> Fixed label for capital work file upload field

Gemfile, Gemfile.lock, config/initializers/silencer.rb
This is a way to reduce log-noise as cloudfoundry is constantly hitting healthcheck endpoint. This is one of the suggestions of papertrail: https://help.papertrailapp.com/kb/configuration/controlling-verbosity#reduce-noise
=> Silence healthcheck

app/views/project/project_capital_works/show.html.erb
With JavaScript disabled, submitting the form on the 'Will capital work be part of your project?' page would throw an `ActionController::InvalidAuthenticityToken` exception. By setting a `no_js` variable inside a `noscript` element, we can then use this flag to determine whether or not to set the `remote` value of the form to `true` or `false`.
I'm not sure whether this is best practice - there might be a built-in Rails way of determining this, but I couldn't find anything when researching.
=> Added flag to enable non-JS journey on Capital Work page

app/controllers/project/project_cash_contribution_controller.rb, app/views/project/project_cash_contribution/show.html.erb
Similar to #223 .
Note that we're reusing code here from other forms with nested attributes in order to display the errors summary group, which we'll split out into a partial at some stage.
=> Added flag to enable non-JS journey on Cash contributions page

app/controllers/project/project_support_evidence_controller.rb, app/views/project/project_support_evidence/show.html.erb
Similar to #223 .
Note that we're reusing code here from other forms with nested attributes in order to display the errors summary group, which we'll split out into a partial at some stage.
=> Added flag to enable non-JS journey on Evidence of support page

config/environments/production.rb
Makes sense to do this now we have CloudFront on production, see https://guides.rubyonrails.org/asset_pipeline.html#cdns-and-the-cache-control-header
=> set long cache time for assets on production

app/views/organisation/summary/show.html.erb
This was causing two project rows to be added to the database, when there should only be one.
=> Set data-turbolinks to false on organisation summary screen

app/models/legal_signatory.rb, config/locales/en.yml
This looks like the simplest way to add this in for now - although it will allow email addresses through in the format of `name@mailserver`, for example.
Note that it is no longer necessary to validate `presence: true` for this field, as it already triggers as part of the email validation. Leaving it in results in two error messages being displayed when no email address is added.
=> Added email validation to legal signatory model and controller

app/controllers/organisation/mission_controller.rb, app/views/organisation/mission/show.html.erb
Watching a Hotjar recording exposed a bug on the organisation mission page - when unchecking a checkbox and submitting the form, the value was not being unset on the database. This pull request fixes this bug, and tidies the code a little in order to pass RuboCop line length validation.
=> Implemented organisation mission fix and tidied controller

app/views/dashboard/show.html.erb, app/views/home/show.html.erb, app/views/organisation/signatories/show.html.erb, app/views/organisation/summary/show.html.erb, app/views/partials/_file_upload_error_summary.html.erb, app/views/partials/_summary_errors.html.erb, app/views/partials/_summary_errors_flash.html.erb, app/views/project/project_capital_works/show.html.erb, app/views/project/project_cash_contribution/show.html.erb, app/views/project/project_costs/show.html.erb, app/views/project/project_non_cash_contributions/show.html.erb, app/views/project/project_support_evidence/show.html.erb, app/views/project/project_volunteers/show.html.erb
As we're now setting this site-wide, there is no need to include individual `data-turbolinks` attributes across the application. This pull request removes each of these individual uses.
=> Removal of individual data-turbolinks attributes

app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/helpers/nlhf_form_builder.rb
Adds a custom form builder and sets it as default. In discussion with @paulmsmith for now we only have helpers to expose the rails generated ID and name, which can be used in conjunction with vanilla partials. This is a building block to enable @paulmsmith to building more reusable components.
=> add custom form builder

spec/controllers/organisation/summary_controller_spec.rb
This pull request adds integration tests for the `organisation/summary_controller`. Note that there is only a `GET` route for this controller.
=> Added integration tests for organisation summary controller

app/controllers/organisation/signatories_controller.rb, app/models/legal_signatory.rb, app/models/organisation.rb, app/views/organisation/signatories/show.html.erb
This pull request contains refactoring of the organisation legal signatories model, view, and controller. We have refactored the view to use the same nested attributes pattern used elsewhere throughout the service.
Note that a new private method has been included in the controller which will remove a second legal signatory if it has been added with empty attributes. We are only required to validate the second legal signatory if it has been passed through the form with no attributes populated. This is possible, and has been enabled using a lambda in the legal_signatory model. However, when ignoring validation, Rails will attempt to store the record - it's possible to reject a nested model on the parent model, but it isn't possible to specify the parameters for this rejection, i.e. only …
=> Refactoring of legal signatories

spec/controllers/organisation/signatories_controller_spec.rb, spec/factories/legal_signatories.rb
This pull request adds integration tests for the `organisation/signatories_controller`.
=> Added integration tests for legal signatories controller

app/views/organisation/summary/show.html.erb
The organisation summary view previously did not contain a row for the organisation's name, nor did it contain the whole address for an organisation - only the first line. This commit addresses both of these issues, as well as tidying up the markup in order to pass RuboCop line length validation when we bring this in.
=> Added missing fields to organisation summary view

spec/features/organisation_spec.rb
This pull request adds a single additional feature test for the creation of an organisation, this time for an unhappy path. I've also cleaned up the code for the existing feature test and added a couple of extra checks in for page content.
We'll have to decide at some point to what level of granularity we want to go with automated acceptance tests - including all unhappy paths, etc.
=> Added a single unhappy path feature test for organisation creation

.github/workflows/continuous-integration-workflow.yml
Our continuous integration workflow GitHub Action started to fail, reporting an error of 'Failed to initialize, postgres service is unhealthy.'.
Searching for the error found that this seems to be a relatively common occurence with GitHub Actions, with no reason given as to why. However, the fix seems to be as simple as adding extra necessary environment variables to the PostgreSQL service - in this case, we already had POSTGRES_USER, but were not setting POSTGRES_PASSWORD or POSTGRES_DB. This commit adds in the missing environment variables, and also sets the PGPASSWORD environment variable for the 'Run tests' step.
See https://github.community/t5/GitHub-Actions/Mysql-service-never-comes-up-healthy-in-action/td-p/38283.
=> Added extra Postgres environment variables to GitHub Action

app/jobs/application_to_salesforce_job.rb
This commit adds an additional log line to log out the application payload which is being sent to Salesforce.
This will enable us to determine whether the main contact date of birth is being set in production.
=> Addition of application payload log

app/views/project/project_check_answers/_best_placed.html.erb, app/views/project/project_check_answers/_involvement.html.erb
A couple of the links on the 'Check your answers' page at the end of the service journey are linking to the wrong pages - this pull request fixes these links.
=> Fixed incorrect links on check your answers page

app/views/dashboard/show.html.erb, config/locales/dashboard.yml, spec/features/organisation_spec.rb, spec/features/project_spec.rb
This pull request abstracts text content from the project dashboard page and moves it into a language dictionary, enabling future translation work.
=> Abstracted strings from dashboard page

app/controllers/project/declaration_controller.rb, app/views/project/declaration/show_confirm_declaration.html.erb, app/views/project/declaration/show_declaration.html.erb, spec/controllers/project/declaration_controller_spec.rb
This commit moves the user research checkbox item from the declaration page to the confirm declaration page. Relevant controllers and integration tests have also been updated.
=> Moved user research declaration to confirm declaration page

spec/features/project_spec.rb
we can simplify this stub as it will break currently if any of the headers change e.g. faraday version.
=> simplify stub

app/views/project/capital_works/show.html.erb, app/views/project/capital_works/show.js.erb
I had missed adding some of the necessary elements/identifiers to the capital works page when refactoring the AJAX error-handling for this view. I believe that this is the cause of the alerts being raised by Sentry in relation to this page.
I've tested locally with this fix in place and can't produce any JavaScript errors on this page (or the other pages with AJAX error-handling).
=> Added missing error elements to capital works view

app/models/project.rb
since we removed the issue of populating empty items in the database this check if no longer required.
=> fix TODO remove redundant name check

app/controllers/released_form_controller.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/environments/test.rb, spec/controllers/released_form_controller_spec.rb
Salesforce webhook expects basic auth. This is part of https://trello.com/c/JHdiuJOH/1111-capture-salesforce-webhook-json-in-db-medium
=> add basic auth to consumer endpoint

app/models/cash_contribution.rb, app/models/non_cash_contribution.rb, app/models/project_cost.rb, app/models/volunteer.rb, app/views/project/cash_contributions/show.html.erb, app/views/project/non_cash_contributions/show.html.erb, app/views/project/volunteers/show.html.erb, config/locales/en.yml, spec/controllers/project/cash_contributions_controller_spec.rb, spec/controllers/project/costs_controller_spec.rb, spec/controllers/project/non_cash_contributions_controller_spec.rb, spec/controllers/project/volunteers_controller_spec.rb
This commit adds validation for fields in the application which capture numerical values. These occur on the following pages - volunteers, non-cash contributions, cash contributions, and project costs. Previously, where no validation occurred, a user could enter a negative integer value and the application would pass this through. This could result in negative values being passed through to Salesforce, or a negative value being displayed on the overall grant request page.
Additionally, I have replaced the remaining numerical fields on the related views with text fields. Originally, we chose to use numerical fields to enable browser-based validation. However, GDS advise not to use input fields with a type attribute of number and to use input fields with a type attribute of text and to …
=> Added validation for negative integers

README.md
remove redundant manual SQL from README as we are now running this in a migration
Added more complete documentation on how to flip switch
=> remove redundant manual SQL from README

app/jobs/release_form_job.rb
This fixes an edge case whereby if a user for example toggles the permission to start on and off this would have created multiple records. This changes to perform an upsert if there in an existing form of that type.
=> perform upsert if same form type sent multiple times

app/models/legal_signatory.rb, app/models/project.rb, spec/models/project_spec.rb
This commit adds the `isAlsoApplicant flag` to the Salesforce payload which is generated from the project model. This flag is used by Salesforce to determine whether or not to create only one Contact object if a user and a legal signatory have the same email address.
As a result, the temporary validation rule we had in place on the legal signatory model has been removed.
N/A
=> Added isAlsoApplicant flag to Salesforce payload

app/models/user.rb
This commit changes the way in which we send Devise notifications (confirm account, reset password, etc.) to send this in a non-blocking way - using ActiveJob.
This has been done as per the guidance in the Devise documentation - overriding the send_devise_notifcation method within the user model.
See https://github.com/heartcombo/devise#activejob-integration for more context.
We didn't have any testing for this area of the application, and it seemed like overkill to start writing new tests to assert that `deliver_later` is called rather than `deliver` - it's something we can pick up separately when we come to test this area.
=> Send Devise notifications asynchronously

app/views/partials/_file_upload_error.html.erb, app/views/partials/_file_upload_error_summary.html.erb, config/locales/en.yml
Bug fix. Previously this message was not displaying correctly because of incorrect indentation in the locales file it was nested under `activerecord`. I have moved it and created a more descriptive namespace.
=> fix direct upload error message

app/views/help/cookie_details.html.erb
Heading was erroneously duplicated.
=> fix heading on cookie details page

app/models/user.rb
Revert this to allow time to investigate broken links: https://trello.com/c/LgVOvR5q/1431-devise-links-in-notify-emails-are-broken
Reverts heritagefund/funding-frontend#379
=> Revert "Send Devise notifications asynchronously"

app/views/organisation/signatories/show.html.erb
Fixes issue found in accessibility review: https://trello.com/c/mXNP8Uh5/1445-alert-fieldset-missing-legend-on-signatories-page-organisation-id-signatories
=> add missing legend for legal signatories

app/views/address/address_results.html.erb
Fixes issue found in accessibility review https://trello.com/c/GQmL2QJ1/782-error-form-label-missing-for-address-results-dropdown-in-organisation-organisation-id-about-address-results
=> fix missing address select label

app/views/funding_application/gp_project/description/show.html.erb, app/views/partials/funding_application/_description_question.html.erb
This commit abstracts the funding application project description markup into a partial so that it can be referenced by multiple application journeys.
N/A.
N/A.
=> Abstracted funding application project description markup into partial

app/views/organisation/signatories/show.html.erb, app/views/partials/organisation/_signatories_question.html.erb
This commit abstracts the organisation signatories markup into a partial so that it can be referenced by multiple application journeys.
N/A.
N/A.
=> Abstracted organisation signatories markup into partial

app/views/organisation/mission/show.html.erb, app/views/partials/organisation/_mission_question.html.erb, app/views/pre_application/org/mission/show.html.erb
This commit abstracts the organisation mission markup into a partial so that it can be referenced by multiple application journeys.
N/A.
N/A.
=> Abstracted organisation mission markup into partial

app/views/organisation/numbers/show.html.erb, app/views/partials/organisation/_numbers_question.html.erb
This commit abstracts the organisation numbers markup into a partial so that it can be referenced by multiple application journeys.
N/A.
N/A.
=> Abstracted organisation numbers markup into partial

config/locales/funding_application/agreement/terms/en.yml
Legal changes to capital work timing for terms of Grant. Now 20 years.
Line 88 has changed, new content added referring to terms of grant for capital projects.
Need to discuss with the devs how and when they can add changes to the applicant only download terms and conditions, and the legal sig download terms and conditions - plus the Welsh versions of these 2 docs for grants of £100 to £250k.
=> Update line 88 en.yml
